### PR TITLE
MS Azure support

### PR DESCRIPTION
**Pull request by merqlove**

### CODE REVIEW

**Comment by chr4** [comment]
This looks very good. Merging, then testing and releasing it in a bit.
Thanks for your contribution!

**Comment by merqlove** [comment]
Ok! :+1: 
Chris, this code written from scratch. 
I'm also will test it in staging later(march), but i think it works as expected.

**Comment by chr4** [comment]
Ok. Let me know how your tests went and whether you have any fixes.
Will wait with the release until we both tested it.

**Comment by merqlove** [comment]
:+1:

**Comment by merqlove** [comment]
Hi @chr4 
I tried from kitchen to upload/download some Azure demo containers.
Works well, like Swift.
Azure SDK version is latest 10.0, so it seems to be ok.
Changes is , upgrade Duplicity to 0.7.02: 
```
"duplicity_ng": {
      "source": {
        "version": "0.7.02",
        "checksum": "609462ba43275340ae4fc008ee6620265cdc2c68988caae289971dd609ed033a",
        "url": "https://launchpad.net/duplicity/0.7-series/0.7.02/+download/duplicity-0.7.02.tar.gz"
      }
}
```

**Comment by merqlove** [comment]
Otherwise duplicity works wrong with Azure.

**Comment by chr4** [comment]
Ok, thanks. Can you force push this pull request to include all changes from both pull-requests?

**Pull request merged**
